<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>NotasFiscais.Application</RootNamespace>
    <AssemblyName>NotasFiscais.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NotasFiscais.Domain\NotasFiscais.Domain.csproj" />
  </ItemGroup>
</Project>
